### PR TITLE
Fix breaking changes from asc v0.9.2

### PR DESCRIPTION
**Pull request by willemneal**
The API for the new expression node changed.  Also a reference to the program now gets passed.

The other big breaking change is the semantics for null checking.

### CODE REVIEW

**Comment by bowenwang1996** [comment]
> The other big breaking change is the semantics for null checking.

What's the change?

**Comment by willemneal** [comment]
I'm still investigating, but the previous way of doing it as `a.x == <T> null` now results in a runtime error, but you can still convert the reference to usize and check that it's 0.

**Comment by willemneal** [comment]
The changes mean that you can't compare things that haven't explicit been typed as possibly null.  However, I added a global convenience function to check if a value is null by checking if it's reference value is zero. `isNull<T>(t: T)`

Also I finally managed to force the assemblyscript dependency to use the already loaded version which means that it can be installed globally and work fine.  Not to mention no bugs from being in a different location.

Lastly, webpack was removed because we are moving away from browser with gitpod and it simplifies the project.

**Comment by vgrichina** [comment]
@willemneal will users of near-bindgen-as need to upgrade anything beside near-bindgen-as?

**Comment by willemneal** [comment]
Assemblyscript now needs to be 0.9.2, but it will fail with a message that says so.

**Comment by willemneal** [comment]
And the runtime needs to be updated concurrently, which I'm about to push.

**Comment by vgrichina** [comment]
@willemneal so we need to update create-near-app, correct?

**Comment by willemneal** [comment]
Yeah but the idea would be to publish this with as a minor update along with near-runtime-ts, so that they won't break any projects depending on the current minor version.  But yeah this will require eventually updating all projects.

**Comment by willemneal** [comment]
@vgrichina Can I merge this and then after getting the newest minor version I can create the `near-devtools` we discussed and ensure all the necessary dependencies are all up to date and then update the example apps to use it?

**Comment by vgrichina** [comment]
@willemneal should be fine to merge, as long as you bump package version accordingly (to prevent depending projects from auto-upgrading) or don't push to npm yet (but also make sure to bump when publishing)

**Review by vgrichina — APPROVED** [review]

**Pull request merged**
